- hosts: tag_name_webserver
  tasks:
         
         - package:
                 name: "httpd"
                 state: present

         - package:
                 name: "php"
                 state: present

         - file:
                 state: directory
                 path: /var/www/webApp

         - template:
                 src: "webApp.conf"
                 dest: "/etc/httpd/conf.d/"

         - copy:
                 src: "index.php"
                 dest: "/var/www/webApp/"

         - service:
                 name: "httpd"
                 state: restarted


